using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace BatToExeConverter.Cn;

internal static class RunnerTemplate
{
    public static string Create(ConversionOptions options, string batchBase64, string appId)
    {
        var chunks = SplitBase64(batchBase64)
            .Select(CSharpLiteral)
            .ToArray();

        var chunksSource = string.Join("," + Environment.NewLine + "        ", chunks);
        var sourceFileName = BuildEmbeddedScriptName(options.SourceBatchPath, appId);
        var logFileName = appId + ".log";

        return $$"""
// <auto-generated />
using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

internal static class Program
{
    [STAThread]
    private static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        RunnerConfig config = RunnerConfig.Create();
        if (config.TrayMode)
        {
            using (var context = new TrayRunnerContext(config))
            {
                Application.Run(context);
            }

            return;
        }

        int exitCode = ScriptRunner.RunAndWait(config);
        Environment.Exit(exitCode);
    }
}

internal sealed class RunnerConfig
{
    public string AppTitle { get; private set; }
    public string AppId { get; private set; }
    public string ScriptFileName { get; private set; }
    public string LogPath { get; private set; }
    public string HomePageUrl { get; private set; }
    public bool TrayMode { get; private set; }
    public bool HideWindow { get; private set; }
    public bool KillOnExit { get; private set; }

    public static RunnerConfig Create()
    {
        string logDirectory = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "BatToExeCn",
            "Logs");

        return new RunnerConfig
        {
            AppTitle = {{CSharpLiteral(options.ApplicationTitle)}},
            AppId = {{CSharpLiteral(appId)}},
            ScriptFileName = {{CSharpLiteral(sourceFileName)}},
            LogPath = Path.Combine(logDirectory, {{CSharpLiteral(logFileName)}}),
            HomePageUrl = {{CSharpLiteral(options.HomePageUrl ?? string.Empty)}},
            TrayMode = {{BoolLiteral(options.TrayMode)}},
            HideWindow = {{BoolLiteral(options.HideWindow)}},
            KillOnExit = {{BoolLiteral(options.KillOnExit)}},
        };
    }
}

internal static class EmbeddedScript
{
    private static readonly string[] Chunks = new string[]
    {
        {{chunksSource}}
    };

    public static byte[] GetBytes()
    {
        return Convert.FromBase64String(string.Concat(Chunks));
    }
}

internal static class ScriptRunner
{
    public static int RunAndWait(RunnerConfig config)
    {
        AppendLog(config, "启动脚本。");
        using (ManagedProcess process = Start(config))
        {
            process.WaitForExit();
            AppendLog(config, "脚本结束，退出码：" + process.ExitCode);
            return process.ExitCode;
        }
    }

    public static ManagedProcess Start(RunnerConfig config)
    {
        string scriptPath = PrepareScript(config);
        Directory.CreateDirectory(Path.GetDirectoryName(config.LogPath));

        var startInfo = new ProcessStartInfo
        {
            FileName = Environment.GetEnvironmentVariable("ComSpec") ?? "cmd.exe",
            UseShellExecute = false,
            CreateNoWindow = config.HideWindow,
            WindowStyle = config.HideWindow ? ProcessWindowStyle.Hidden : ProcessWindowStyle.Normal,
            WorkingDirectory = AppContext.BaseDirectory,
        };

        startInfo.Arguments = "/d /c " + QuoteForCmd(scriptPath);

        if (config.HideWindow)
        {
            startInfo.RedirectStandardOutput = true;
            startInfo.RedirectStandardError = true;
            startInfo.StandardOutputEncoding = Encoding.Default;
            startInfo.StandardErrorEncoding = Encoding.Default;
        }

        var process = new Process { StartInfo = startInfo, EnableRaisingEvents = true };
        if (config.HideWindow)
        {
            process.OutputDataReceived += (_, eventArgs) =>
            {
                if (!string.IsNullOrEmpty(eventArgs.Data))
                {
                    AppendLog(config, eventArgs.Data);
                }
            };
            process.ErrorDataReceived += (_, eventArgs) =>
            {
                if (!string.IsNullOrEmpty(eventArgs.Data))
                {
                    AppendLog(config, eventArgs.Data);
                }
            };
        }

        process.Start();
        ChildProcessJob job = null;
        if (config.TrayMode)
        {
            job = ChildProcessJob.TryCreate(config, config.KillOnExit);
            if (job != null)
            {
                job.AddProcess(config, process);
            }
        }

        if (config.HideWindow)
        {
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
        }

        return new ManagedProcess(process, job);
    }

    public static void AppendLog(RunnerConfig config, string message)
    {
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(config.LogPath));
            File.AppendAllText(
                config.LogPath,
                DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + "  " + message + Environment.NewLine,
                Encoding.UTF8);
        }
        catch
        {
        }
    }

    private static string PrepareScript(RunnerConfig config)
    {
        byte[] scriptBytes = EmbeddedScript.GetBytes();
        string[] directories = ResolveWritableDirectories(config);
        Exception lastError = null;

        foreach (string directory in directories)
        {
            try
            {
                Directory.CreateDirectory(directory);
                CleanupOldScripts(directory, config);

                string scriptPath = BuildUniqueScriptPath(directory, config);
                File.WriteAllBytes(scriptPath, scriptBytes);

                try
                {
                    File.SetAttributes(scriptPath, File.GetAttributes(scriptPath) | FileAttributes.Hidden);
                }
                catch
                {
                }

                return scriptPath;
            }
            catch (Exception ex)
            {
                lastError = ex;
                AppendLog(config, "脚本写入失败：" + directory + "，" + ex.Message);
            }
        }

        throw new InvalidOperationException("无法写入运行脚本。" + (lastError == null ? string.Empty : " " + lastError.Message));
    }

    private static string BuildUniqueScriptPath(string directory, RunnerConfig config)
    {
        string extension = Path.GetExtension(config.ScriptFileName);
        if (string.IsNullOrEmpty(extension))
        {
            extension = ".bat";
        }

        string name = Path.GetFileNameWithoutExtension(config.ScriptFileName);
        string suffix = "_" + Process.GetCurrentProcess().Id.ToString() + "_" + DateTime.Now.ToString("yyyyMMddHHmmssfff");
        return Path.Combine(directory, name + suffix + extension);
    }

    private static string QuoteForCmd(string value)
    {
        return "\"" + value.Replace("\"", "\\\"") + "\"";
    }

    private static void CleanupOldScripts(string directory, RunnerConfig config)
    {
        try
        {
            string name = Path.GetFileNameWithoutExtension(config.ScriptFileName);
            string extension = Path.GetExtension(config.ScriptFileName);
            foreach (string file in Directory.GetFiles(directory, name + "*" + extension))
            {
                try
                {
                    File.SetAttributes(file, FileAttributes.Normal);
                    File.Delete(file);
                }
                catch
                {
                }
            }
        }
        catch
        {
        }
    }

    private static string[] ResolveWritableDirectories(RunnerConfig config)
    {
        string baseDirectory = AppContext.BaseDirectory;
        string tempDirectory = Path.Combine(Path.GetTempPath(), "BatToExeCn", config.AppId);
        return new string[] { baseDirectory, tempDirectory };
    }

    private static bool CanWriteToDirectory(string directory, RunnerConfig config)
    {
        try
        {
            Directory.CreateDirectory(directory);
            string probe = Path.Combine(directory, "." + config.AppId + ".probe_" + Process.GetCurrentProcess().Id.ToString());
            File.WriteAllText(probe, string.Empty);
            File.Delete(probe);
            return true;
        }
        catch
        {
            return false;
        }
    }
}

internal sealed class ManagedProcess : IDisposable
{
    private readonly Process _process;
    private ChildProcessJob _job;

    public ManagedProcess(Process process, ChildProcessJob job)
    {
        _process = process;
        _job = job;
    }

    public bool HasExited
    {
        get
        {
            try
            {
                return _process.HasExited;
            }
            catch
            {
                return true;
            }
        }
    }

    public int ExitCode
    {
        get { return _process.ExitCode; }
    }

    public void WaitForExit()
    {
        _process.WaitForExit();
    }

    public void KillProcessGroup()
    {
        try
        {
            if (!_process.HasExited)
            {
                _process.Kill();
            }
        }
        catch
        {
        }

        if (_job != null)
        {
            _job.Terminate();
            _job.Dispose();
        }
        _job = null;
    }

    public void Dispose()
    {
        if (_job != null)
        {
            _job.Dispose();
            _job = null;
        }
        _process.Dispose();
    }
}

internal sealed class ChildProcessJob : IDisposable
{
    private const int JobObjectExtendedLimitInformationClass = 9;
    private const uint JobObjectLimitKillOnJobClose = 0x00002000;

    private IntPtr _handle;
    private readonly RunnerConfig _config;

    private ChildProcessJob(IntPtr handle, RunnerConfig config)
    {
        _handle = handle;
        _config = config;
    }

    public static ChildProcessJob TryCreate(RunnerConfig config, bool killOnClose)
    {
        IntPtr handle = CreateJobObject(IntPtr.Zero, null);
        if (handle == IntPtr.Zero)
        {
            ScriptRunner.AppendLog(config, "创建进程组失败，错误码：" + Marshal.GetLastWin32Error());
            return null;
        }

        var information = new JobObjectExtendedLimitInformation
        {
            BasicLimitInformation = new JobObjectBasicLimitInformation
            {
                LimitFlags = killOnClose ? JobObjectLimitKillOnJobClose : 0u,
            },
        };

        int length = Marshal.SizeOf<JobObjectExtendedLimitInformation>();
        IntPtr pointer = Marshal.AllocHGlobal(length);
        try
        {
            Marshal.StructureToPtr(information, pointer, false);
            if (!SetInformationJobObject(handle, JobObjectExtendedLimitInformationClass, pointer, (uint)length))
            {
                ScriptRunner.AppendLog(config, "配置进程组失败，错误码：" + Marshal.GetLastWin32Error());
                CloseHandle(handle);
                return null;
            }
        }
        finally
        {
            Marshal.FreeHGlobal(pointer);
        }

        return new ChildProcessJob(handle, config);
    }

    public void AddProcess(RunnerConfig config, Process process)
    {
        if (_handle == IntPtr.Zero)
        {
            return;
        }

        if (!AssignProcessToJobObject(_handle, process.Handle))
        {
            ScriptRunner.AppendLog(config, "加入进程组失败，错误码：" + Marshal.GetLastWin32Error());
        }
    }

    public void Terminate()
    {
        if (_handle == IntPtr.Zero)
        {
            return;
        }

        if (!TerminateJobObject(_handle, 1u))
        {
            ScriptRunner.AppendLog(_config, "终止进程组失败，错误码：" + Marshal.GetLastWin32Error());
        }
    }

    public void Dispose()
    {
        if (_handle != IntPtr.Zero)
        {
            CloseHandle(_handle);
            _handle = IntPtr.Zero;
        }

        GC.SuppressFinalize(this);
    }

    ~ChildProcessJob()
    {
        Dispose();
    }

    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern IntPtr CreateJobObject(IntPtr jobAttributes, string name);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool SetInformationJobObject(IntPtr job, int jobObjectInformationClass, IntPtr jobObjectInformation, uint jobObjectInformationLength);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool AssignProcessToJobObject(IntPtr job, IntPtr process);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool TerminateJobObject(IntPtr job, uint exitCode);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool CloseHandle(IntPtr handle);

    [StructLayout(LayoutKind.Sequential)]
    private struct JobObjectBasicLimitInformation
    {
        public long PerProcessUserTimeLimit;
        public long PerJobUserTimeLimit;
        public uint LimitFlags;
        public UIntPtr MinimumWorkingSetSize;
        public UIntPtr MaximumWorkingSetSize;
        public uint ActiveProcessLimit;
        public IntPtr Affinity;
        public uint PriorityClass;
        public uint SchedulingClass;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct IoCounters
    {
        public ulong ReadOperationCount;
        public ulong WriteOperationCount;
        public ulong OtherOperationCount;
        public ulong ReadTransferCount;
        public ulong WriteTransferCount;
        public ulong OtherTransferCount;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct JobObjectExtendedLimitInformation
    {
        public JobObjectBasicLimitInformation BasicLimitInformation;
        public IoCounters IoInfo;
        public UIntPtr ProcessMemoryLimit;
        public UIntPtr JobMemoryLimit;
        public UIntPtr PeakProcessMemoryUsed;
        public UIntPtr PeakJobMemoryUsed;
    }
}

internal sealed class TrayRunnerContext : ApplicationContext
{
    private readonly RunnerConfig _config;
    private readonly NotifyIcon _notifyIcon;
    private readonly ToolStripMenuItem _statusItem;
    private readonly ToolStripMenuItem _runItem;
    private readonly ToolStripMenuItem _stopItem;
    private ManagedProcess _process;

    public TrayRunnerContext(RunnerConfig config)
    {
        _config = config;
        _statusItem = new ToolStripMenuItem("状态：准备运行") { Enabled = false };
        _runItem = new ToolStripMenuItem("重新运行脚本", null, (sender, eventArgs) => RunScriptAsync());
        _stopItem = new ToolStripMenuItem("停止脚本", null, (sender, eventArgs) => StopScriptGroup()) { Enabled = false };

        var menu = new ContextMenuStrip();
        menu.Items.Add(_statusItem);
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add(_runItem);
        menu.Items.Add(_stopItem);
        if (!string.IsNullOrWhiteSpace(config.HomePageUrl))
        {
            menu.Items.Add("打开主页", null, (sender, eventArgs) => OpenHomePage());
        }
        menu.Items.Add("打开日志", null, (sender, eventArgs) => OpenLog());
        menu.Items.Add("打开程序目录", null, (sender, eventArgs) => OpenAppDirectory());
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("退出", null, (sender, eventArgs) => ExitThread());

        _notifyIcon = new NotifyIcon
        {
            Text = ShortText(config.AppTitle),
            Icon = ResolveIcon(),
            ContextMenuStrip = menu,
            Visible = true,
        };
        _notifyIcon.DoubleClick += (sender, eventArgs) => OpenLog();
        _notifyIcon.ShowBalloonTip(2500, config.AppTitle, "程序已在系统托盘运行。", ToolTipIcon.Info);

        RunScriptAsync();
    }

    private async void RunScriptAsync()
    {
        if (_process != null && !_process.HasExited)
        {
            _notifyIcon.ShowBalloonTip(2500, _config.AppTitle, "脚本仍在运行。", ToolTipIcon.Info);
            return;
        }

        StopScriptGroup(showMessage: false);
        _runItem.Enabled = false;
        _stopItem.Enabled = true;
        _statusItem.Text = "状态：运行中";
        ScriptRunner.AppendLog(_config, "托盘模式启动脚本。");

        try
        {
            _process = ScriptRunner.Start(_config);
            await Task.Run(() => _process.WaitForExit());
            int exitCode = _process.ExitCode;
            if (_config.KillOnExit)
            {
                _statusItem.Text = "状态：入口已结束，子进程由托盘托管";
                ScriptRunner.AppendLog(_config, "入口脚本结束，退出码：" + exitCode + "。托盘退出时会清理子进程。");
            }
            else
            {
                _statusItem.Text = "状态：已结束，退出码 " + exitCode;
                ScriptRunner.AppendLog(_config, "脚本结束，退出码：" + exitCode);
            }
        }
        catch (Exception ex)
        {
            _statusItem.Text = "状态：运行失败";
            ScriptRunner.AppendLog(_config, "运行失败：" + ex.Message);
            _notifyIcon.ShowBalloonTip(3500, _config.AppTitle, "运行失败：" + ex.Message, ToolTipIcon.Error);
        }
        finally
        {
            _runItem.Enabled = true;
            _stopItem.Enabled = _process != null;
        }
    }

    protected override void ExitThreadCore()
    {
        if (_config.KillOnExit)
        {
            if (_process != null)
            {
                _process.KillProcessGroup();
            }
        }
        if (_process != null)
        {
            _process.Dispose();
        }
        _notifyIcon.Visible = false;
        _notifyIcon.Dispose();
        base.ExitThreadCore();
    }

    private void StopScriptGroup(bool showMessage = true)
    {
        if (_process == null)
        {
            return;
        }

        _process.KillProcessGroup();

        _process.Dispose();
        _process = null;
        _stopItem.Enabled = false;
        _statusItem.Text = "状态：已停止";
        ScriptRunner.AppendLog(_config, "已停止脚本进程组。");

        if (showMessage)
        {
            _notifyIcon.ShowBalloonTip(2500, _config.AppTitle, "脚本进程组已停止。", ToolTipIcon.Info);
        }
    }

    private void OpenLog()
    {
        if (!File.Exists(_config.LogPath))
        {
            MessageBox.Show("当前还没有日志。", _config.AppTitle, MessageBoxButtons.OK, MessageBoxIcon.Information);
            return;
        }

        Process.Start(new ProcessStartInfo
        {
            FileName = _config.LogPath,
            UseShellExecute = true,
        });
    }

    private void OpenHomePage()
    {
        if (string.IsNullOrWhiteSpace(_config.HomePageUrl))
        {
            return;
        }

        Process.Start(new ProcessStartInfo
        {
            FileName = _config.HomePageUrl,
            UseShellExecute = true,
        });
    }

    private static void OpenAppDirectory()
    {
        Process.Start(new ProcessStartInfo
        {
            FileName = AppContext.BaseDirectory,
            UseShellExecute = true,
        });
    }

    private static Icon ResolveIcon()
    {
        try
        {
            return Icon.ExtractAssociatedIcon(Application.ExecutablePath) ?? SystemIcons.Application;
        }
        catch
        {
            return SystemIcons.Application;
        }
    }

    private static string ShortText(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "BAT 转 EXE";
        }

        return value.Length > 60 ? value.Substring(0, 60) : value;
    }
}
""";
    }

    private static string[] SplitBase64(string value)
    {
        const int chunkSize = 3800;
        var count = (value.Length + chunkSize - 1) / chunkSize;
        var result = new string[count];
        for (var i = 0; i < count; i++)
        {
            var start = i * chunkSize;
            var length = Math.Min(chunkSize, value.Length - start);
            result[i] = value.Substring(start, length);
        }

        return result;
    }

    private static string BuildEmbeddedScriptName(string sourceBatchPath, string appId)
    {
        var extension = Path.GetExtension(sourceBatchPath);
        if (!string.Equals(extension, ".bat", StringComparison.OrdinalIgnoreCase) &&
            !string.Equals(extension, ".cmd", StringComparison.OrdinalIgnoreCase))
        {
            extension = ".cmd";
        }

        return "." + appId + "_script" + extension.ToLowerInvariant();
    }

    private static string BoolLiteral(bool value)
    {
        return value ? "true" : "false";
    }

    private static string CSharpLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => ch.ToString(),
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
